server:
  port: 8082
bot:
  token: ${TOKEN}
  name: ${NAME}

spring:
  application:
    name: bot service
  cloud:
    compatibility-verifier:
      enabled: false
  mail:
    host: smtp.yandex.ru
    port: 465
    username: ${MAIL_LOGIN}
    password: ${MAIL_PASS}
    test-connection: true # проверка подключения при старте приложения
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
          starttls:
            enable: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory

---
spring:
  main:
    allow-circular-references: true
  profiles:
    active: dev

  datasource:
    url: jdbc:postgresql://localhost:5432/bot
    username: admin
    password: admin