server:
  port: 8082
bot:
  token: ${TOKEN}
  name: ${NAME}
spring:
  application:
    name: bot-service
  cloud:
    compatibility-verifier:
      enabled: false
  mail:
    host: smtp.yandex.ru
    port: 465
    username: ${MAIL_LOGIN}
    password: ${MAIL_PASS}
    test-connection: true # проверка подключения при старте приложения
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
          starttls:
            enable: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
kafka:
  server: localhost # kafka ip
  port: 9092 #kafka port
  topic: telegram-bot-topic
  consumer:
    id: kafka-consumer-telegrambot-svc
    group:
      id: kafka-consumer-telegrambot-svc
---
spring:
  sql:
    init:
      mode: always
  main:
    allow-circular-references: true
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/bot
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
